world/config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "components" => "components#index"

  get "classes/index", as: :classes_index

  get "users/me" => "me#index", as: :me_index
  get "users/me/mentor/availability" => "me#show_mentor_availability", as: :me_mentor_availability
  post "users/me/mentor/availability_date" => "me#show_mentor_availability_date", as: :me_mentor_availability_by_date
  post "users/me/mentor/opt" => "me#opt_mentor", as: :me_mentor_opt
  post "users/me/bio" => "me#update_bio", as: :me_bio_update

  get "users/:user_id/profile_picture/large" => "users#large_profile_picture", as: :large_profile_picture
  get "users/:user_id/profile_picture" => "users#profile_picture", as: :profile_picture
  post "users/:user_id/skills/:skill_id/endorse" => "users#endorse_skill"

  resources :mentors, only: [ :index, :show ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

world/app/models/mentor.rb
class Mentor
    def self.all
        User.where(is_mentor: true)
    end

    def self.find(id)
        User.find_by(id: id, is_mentor: true)
    end
end

world/app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
  before_action :authenticate_user!, only: [ :index ]

  def index
    @mentors = Mentor.all
  end

  def show
    @mentor = Mentor.find(params[:id])

    if @mentor.nil?
      render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
    end
  end
end

world/app/helpers/mentors_helper.rb
module MentorsHelper
end

world/app/views/mentors/index.html.erb
<%= render :partial => "shared/responsive_navbar", :locals => { active_menu: "mentors" } %>

<section class="w-full">
  <div class="mx-auto text-center py-20">
    <h1 class="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Looking for a mentor?</h1>
    <p class="mt-6 text-lg leading-8 text-slate-600">These people may help you.</p>
  </div>
  <div class="w-full flex flex-col items-center">
    <% if @mentors.length == 0 %>
      <div class="mx-auto text-center">
          <p class="text-xl lg:text-4xl">Sorry, no mentors available right now.<br>Maybe try again later?</p>
      </div>
    <% else %>
      <div class="max-w-4xl w-full grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 place-items-stretch gap-4 px-8 md:px-4 lg:px-0">
        <% @mentors.each do |mentor| %>
          <%= link_to mentor_path(mentor.id) do %>
            <%= render :partial => "shared/mentor_card", :locals => { mentor: mentor } %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</section>

world/app/views/mentors/show.html.erb
<%= render :partial => "shared/responsive_navbar", :locals => { active_menu: "mentors" } %>

<section class="w-full py-8">
  <div class="w-full max-w-4xl grid grid-cols-3 md:grid-cols-6 lg:grid-cols-8 mx-auto gap-x-8 gap-y-4 px-4 lg:px-0">
    <div class="col-span-1 md:col-span-2 lg:col-span-3">
        <%= render :partial => "shared/large_profile_picture", :locals => { user: @mentor } %>
    </div>
    <div class="col-span-2 md:col-span-4 lg:col-span-5">
        <h2 class="text-2xl font-bold text-slate-800"><%= @mentor.fullname %></h2>
        <p class="font-normal text-lg mt-2"><%= @mentor.bio %></p>
        <% if @mentor.skills.length > 0 %>
          <div class="mt-8">
            <ul class="m-0 p-0 flex flex-row flex-wrap gap-2 align-top justify-start">
              <% @mentor.skills.each do |skill| %>
                <li>
                  <%= render :partial => "shared/skill", :locals => { skill: skill, skills_users_assoc: skill.skills_users.find_by(skill_id: skill.id, user_id: @mentor.id) } %>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
    </div>
  </div>
</section>