feedback/config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'class_feedbacks/index'
    get 'courses_rating/index'
  end
  get 'class_feedbacks/new'
  post 'class_feedbacks/create'
  get 'home/index'
  get 'thank_you', to: 'thank#thank_you'
  get 'summarize_feedback/:class_detail_id', to: 'summarize_feedback#summarize_feedback'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # scope 'api' do
  #   get 'class_feedbacks', to: 'class_feedback#index'
  #   get 'courses_rating', to: 'courses_rating#index'
  # end
end

feedback/app/models/class_detail.rb
class ClassDetail < ApplicationRecord
end

feedback/app/models/class_feedback.rb
class ClassFeedback < ApplicationRecord
  belongs_to :class_detail
end

feedback/app/controllers/api/class_feedbacks_controller.rb
class Api::ClassFeedbacksController < ApplicationController
  def index
    render json: ClassFeedback.all
  end
end

feedback/app/controllers/api/courses_rating_controller.rb
class Api::CoursesRatingController < ApplicationController
    def index
        courses_rating = ClassFeedback
        .select(:class_detail_id, 'ROUND( AVG(rating), 2 ) AS average_rating')
        .group(:class_detail_id)

        render json: (courses_rating), except: ['id']
    end
end

feedback/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

feedback/app/controllers/class_feedbacks_controller.rb
class ClassFeedbacksController < ApplicationController
  def new
    @class_feedback = ClassFeedback.new
    @class_feedback.class_detail_id = params[:class_id]
  end

  def create
    puts params
    puts params[:rating]
    puts params[:comment]
    puts params[:recommend]
    puts params[:rating_trainer]
    class_feedback_params = params.require(:class_feedback).permit(:rating , :recommend, :comment, :rating_trainer, :class_detail_id)
    @class_feedback = ClassFeedback.new(class_feedback_params)
    # respond_to do |format|
    if @class_feedback.save
      # format.turbo_stream
      # format.html do
        # render "thank/thank_you"
        redirect_to thank_you_path
      # end
    end
    # end
  end
end

feedback/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    @class_feedbacks = ClassFeedback.all
    @class_list = ClassDetail.all
  end
end

feedback/app/controllers/summarize_feedback_controller.rb
class SummarizeFeedbackController < ApplicationController
    def summarize_feedback
      logger.debug params[:class_detail_id].class

      @class_feedback = ClassFeedback
        .where(class_detail_id: params[:class_detail_id])
        .order(params[:sort])
        .reverse
      @class_detail = ClassDetail
      @record_count = ClassFeedback
        .where(class_detail_id: params[:class_detail_id])
        .select(:class_detail_id)
        .count
      @courses_rating = ClassFeedback
      .select(:class_detail_id, 'ROUND( AVG(rating), 2 ) AS average_rating')
      .group(:class_detail_id)
      .having(class_detail_id: params[:class_detail_id])
      .first
      
      @recommend = (ClassFeedback
      .where(class_detail_id: params[:class_detail_id])
      .group(:recommend)
      .count[true]/@record_count.to_f*100).round(2)

  
      @trainer_rating = ClassFeedback
      .select(:class_detail_id, 'ROUND( AVG(rating_trainer), 2 ) AS average_trainer_rating')
      .group(:class_detail_id)
      .having(class_detail_id: params[:class_detail_id])
      .first
  



  
  


  
    
      

    
    end
  end
  

feedback/app/controllers/thank_controller.rb
class ThankController < ApplicationController
    def thank_you
      
    end
  end
  

feedback/app/helpers/api/class_feedbacks_helper.rb
module Api::ClassFeedbacksHelper
end

feedback/app/helpers/api/courses_rating_helper.rb
module Api::CoursesRatingHelper
end

feedback/app/helpers/class_feedbacks_helper.rb
module ClassFeedbacksHelper
end

feedback/app/views/class_details/_class_detail.html.erb
<div id="<%= dom_id class_detail %>>">
  
   <%= link_to class_detail.name, class_feedbacks_new_path(:class_id => class_detail.id) %>
</div>

feedback/app/views/home/index.html.erb
<h1>ODDS-TEAM </h1>
    <%= turbo_stream_from "new_class_feedback" %>
    <div>
      <div id="class-feedbacks">
        <%= render @class_list %>
      </div>
    </div>

      

feedback/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Feedback</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

feedback/app/views/summarize_feedback/summarize_feedback.html.erb
  <%= form_with url: 'summarize_feedback', local: true, method: :post do |form| %>
<body>
<h1>Summarize Feedback</h1>
         <div >
                <div class = li>
                        
                        <div class = box >
                            <p class = text-left >Avg Class Rating </p>
                                <h2 class = text-center>
                                    <%= @courses_rating[:average_rating] %>/5 
                                </h2>
                        </div> 
                        <div class = box >
                            <p>Avg Trainer Rating</p>
                                <h2 class = text-center >
                                 <%= @trainer_rating[:average_trainer_rating] %>/5
                                </h2>
                        </div>
                        <div class = box >
                            <p class = text-left >Reccommend </p>
                            <h2 class = text-center >
                                <%= @recommend %> %
                            </h2>
                        </div>
                        <div class = box >
                            <p class = text-left >Record Count </p>
                            <h2 class = text-center>
                                <%= @record_count%>
                            </h2>
                        </div>
            
                    </div>
   <table>
        <tr class = text-center >
            <div>
                <th>Submitted date</th>
                <th>Class Rating</th>
                <th>Trainer Rating</th>
                <th>Comment</th>
                <th>Recommend</th>
            </div>
        </tr>
   
        <% @class_feedback.each do |class_feedback| %> 
             <tr>
            
                    <td><%= class_feedback.created_at %></td>
                    <td><%= class_feedback.rating %></td>
                    <td><%= class_feedback.rating_trainer %> </td>
                    <td><%= class_feedback.comment %> </td>  
                    <td><%= class_feedback.recommend %> </td>
            </tr>  
        <% end %> 
    </table>
    </div>


                    
<% end %>

</body>

feedback/app/views/thank/thank_you.html.erb
<body>
<div class = inputfeedback > 
    <div class = thankimage> </div>
    <div class = text-center>   
        <p>Thank for submitting your feedback. </p>
            <p> We really appreciate your time. </p>

                    <%= link_to "Explore more🕵🏻‍♂️", home_index_path , class: "submit-button button" %>
                    </div>
                </div>
        </div>

</div>
</body>