world/config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "components" => "components#index"

  get "classes/index", as: :classes_index

  get "users/me" => "me#index", as: :me_index
  get "users/me/mentor/availability" => "me#show_mentor_availability", as: :me_mentor_availability
  post "users/me/mentor/availability_date" => "me#show_mentor_availability_date", as: :me_mentor_availability_by_date
  post "users/me/mentor/opt" => "me#opt_mentor", as: :me_mentor_opt
  post "users/me/bio" => "me#update_bio", as: :me_bio_update

  get "users/:user_id/profile_picture/large" => "users#large_profile_picture", as: :large_profile_picture
  get "users/:user_id/profile_picture" => "users#profile_picture", as: :profile_picture
  post "users/:user_id/skills/:skill_id/endorse" => "users#endorse_skill"

  resources :mentors, only: [ :index, :show ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

world/app/controllers/me_controller.rb
class MeController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @me = User.find(current_user.id)
  end

  def show_mentor_availability
  end

  def show_mentor_availability_date
    @selected_date = {
      wday: Date.new(params[:year].to_i, params[:month].to_i, params[:date].to_i).wday,
      date: params[:date],
      month: params[:month],
      year: params[:year]
    }

    respond_to do |format|
      format.turbo_stream {
        render turbo_stream:
        turbo_stream
          .replace("available_date",
          partial: "mentor_available_date",
          locals: { selected_date: @selected_date })
      }
      format.html { redirect_to "/users/me" }
    end
  end

  def opt_mentor
    @me = User.find(current_user.id)
    @me.is_mentor = !@me.is_mentor

    respond_to do |format|
      if @me.save
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream
              .replace("opt_mentor",
                partial: 'mentor_opt_in_button',
                locals: { is_mentor: @me.is_mentor }),
            turbo_stream.replace("mentor_availability",
                partial: 'shared/mentor_availability_link',
                locals: { is_mentor: @me.is_mentor }),
            turbo_stream.replace("my_mentor_status",
                partial: 'me/my_mentor_status',
                locals: { is_mentor: @me.is_mentor })
          ]
        end
        format.html { redirect_to "/users/me" }
      else
      end
    end
  end

  def update_bio
    @me = User.find(current_user.id)
    @me.bio = params[:bio]

    respond_to do |format|
      if @me.save
        format.turbo_stream {
          render turbo_stream: 
          turbo_stream.replace("me_bio",
          partial: 'editable_bio',
          locals: { text: @me.bio } )
        }
        format.html { redirect_to "/users/me" }
      else
      end
    end
  end
end

world/app/helpers/me_helper.rb
module MeHelper
end

world/app/views/me/_editable_bio.html.erb
<%= turbo_frame_tag "me_bio", data: { turbo_cache_control: "no-cache" } do %>
    <p class="font-normal text-lg mt-2">
        <%= form_with   url: me_bio_update_path, 
                        class: "flex flex-row items-center space-x-1", 
                        data: { 
                            controller: "form-sensor",
                            action: "bio:changed->form-sensor#submit"
                        } do |form| %>
            <%= render  "shared/editable_label",
                        text: text,
                        identifier: "bio" %>
        <% end %>
    </p>
<% end %>

world/app/views/me/_mentor_available_date.html.erb
<%= turbo_frame_tag "available_date", data: { turbo_cache_control: "no-cache" } do %>
    <%= form_with url: me_mentor_availability_by_date_path, 
            data: { 
                controller: "form-sensor",
                action: "availability_calendar:selected@window->form-sensor#submit"
            } do |form| %>
        <input type="hidden" data-form-sensor-target="date" name="date">
        <input type="hidden" data-form-sensor-target="month" name="month">
        <input type="hidden" data-form-sensor-target="year" name="year">
    <% end %>
    <div class="flex flex-row justify-between items-center">
        <h2 class="font-bold text-lg"><%= "#{Date::ABBR_DAYNAMES[selected_date[:wday].to_i]} #{selected_date[:date]} #{Date::ABBR_MONTHNAMES[selected_date[:month].to_i]} #{selected_date[:year]}" %></h2>
        <button class="p-2 w-8 h-8 text-slate-600 bg-gray-100 border shadow-sm round rounded">
            <svg xmlns="https://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path d="M12 4l0 16" fill="none" stroke-linejoin="round" stroke-width="4" stroke-linecap="round" stroke="currentColor" />
                <path d="M4 12l16 0" fill="none" stroke-linejoin="round" stroke-width="4" stroke-linecap="round" stroke="currentColor" />
            </svg>
        </button>
    </div>
<% end %>

world/app/views/me/_mentor_opt_in_button.html.erb
<%= turbo_frame_tag "opt_mentor", data: { turbo_cache_control: "no-cache" } do %>
    <% if is_mentor %>
        <%= button_to me_mentor_opt_path, class:"bg-indigo-600 border-transparent border-2 rounded-full cursor-pointer flex-shrink-0 !w-11 !h-6 inline-flex relative" do %>
            <span class="absolute w-5 h-5 rounded-full bg-white shadow right-0"></span>
        <% end %>
    <% else %>
        <%= button_to me_mentor_opt_path, class:"bg-gray-200 border-transparent border-2 rounded-full cursor-pointer flex-shrink-0 !w-11 !h-6 inline-flex relative" do %>
            <span class="w-5 h-5 rounded-full bg-white shadow"></span>
        <% end %>
    <% end %>
<% end %>

world/app/views/me/_my_mentor_status.html.erb
<%= turbo_frame_tag "my_mentor_status", data: { turbo_cache_control: "no-cache" } do %>
  <% if is_mentor %>
    I am a mentor
  <% else %>
    I want to be a mentor
  <% end %>
<% end %>

world/app/views/me/_new_availability.html.erb
<div class="relative transform overflow-hidden rounded-md bg-white text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg" @click.outside="availabilityModalOpen = false" x-show="availabilityModalOpen">
    <%= form_with url: me_bio_update_path do |form| %>
    <div class="bg-white">
        <div class="border-b p-4 flex flex-row justify-between items-start">
            <h2 class="font-bold text-lg text-slate-600">Add availability</h2>
            <button @click="availabilityModalOpen = false" class="w-4 h-4 text-gray-500">
                <svg xmlns="https://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <path d="M4 4l16 16" fill="none" stroke-linejoin="round" stroke-width="4" stroke-linecap="round" stroke="currentColor" />
                    <path d="M20 4l-16 16" fill="none" stroke-linejoin="round" stroke-width="4" stroke-linecap="round" stroke="currentColor" />
                </svg>
            </button>
        </div>
        <div class="py-4 px-8 flex flex-row items-center gap-x-3">
            <div class="w-5 h-5 text-gray-500">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <rect x="1.5" y="1.5" width="21" height="21" rx=2 fill="none" stroke="currentColor" stroke-width="3" />
                    <path d="M1.5 9l21 0" fill="none" stroke-linejoin="round" stroke-width="3" stroke-linecap="round" stroke="currentColor" />
                    <path d="M5 12l0 2.5l2.5 0l0 -2.5Z" fill="currentColor" stroke-width="0" />
                    <path d="M10.75 12l0 2.5l2.5 0l0 -2.5Z" fill="currentColor" stroke-width="0" />
                    <path d="M16.5 12l0 2.5l2.5 0l0 -2.5Z" fill="currentColor" stroke-width="0" />
                    <path d="M5 16.5l0 2.5l2.5 0l0 -2.5Z" fill="currentColor" stroke-width="0" />
                    <path d="M10.75 16.5l0 2.5l2.5 0l0 -2.5Z" fill="currentColor" stroke-width="0" />
                    <path d="M16.5 16.5l0 2.5l2.5 0l0 -2.5Z" fill="currentColor" stroke-width="0" />
                </svg>
            </div>
            <div class="flex flex-row">
                <input type="hidden" name="selectedDate" x-model="selectedDate">
                <span x-html="readableSelectedDate"></span>
            </div>
        </div>
        <div class="py-4 px-8 flex flex-row items-center gap-x-3">
            <div class="w-5 h-5 text-gray-500">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <circle cx="12" cy="12" r="10.5" fill="none" stroke="currentColor" stroke-width="3" />
                    <path d="M12 5l0 7l4 4" fill="none" stroke-linejoin="round" stroke-width="3" stroke-linecap="round" stroke="currentColor" />
                </svg>
            </div>
            <div class="flex flex-col" x-data="{ selectedDays:{sun:{selected:false,from:0,to:15},mon:{selected:true,from:0,to:15},tue:{selected:true,from:0,to:15},wed:{selected:true,from:0,to:15},thu:{selected:true,from:0,to:15},fri:{selected:true,from:0,to:15},sat:{selected:false,from:0,to:15}} }" x-init="$watch('selectedDays', (value) => console.log(value))">
                <input type="hidden" name="sun_selected" x-model="selectedDays.sun.selected">
                <input type="hidden" name="sun_from" x-model="selectedDays.sun.from">
                <input type="hidden" name="sun_to" x-model="selectedDays.sun.to">
                <%= render(DayAvailabilityFieldComponent.new(label: "Sun", selected: false, model: "selectedDays.sun")) %>
                <input type="hidden" name="mon_selected" x-model="selectedDays.mon.selected">
                <input type="hidden" name="mon_from" x-model="selectedDays.mon.from">
                <input type="hidden" name="mon_to" x-model="selectedDays.mon.to">
                <%= render(DayAvailabilityFieldComponent.new(label: "Mon", selected: true, model: "selectedDays.mon")) %>
                <input type="hidden" name="tue_selected" x-model="selectedDays.tue.selected">
                <input type="hidden" name="tue_from" x-model="selectedDays.tue.from">
                <input type="hidden" name="tue_to" x-model="selectedDays.tue.to">
                <%= render(DayAvailabilityFieldComponent.new(label: "Tue", selected: true, model: "selectedDays.tue")) %>
                <input type="hidden" name="wed_selected" x-model="selectedDays.wed.selected">
                <input type="hidden" name="wed_from" x-model="selectedDays.wed.from">
                <input type="hidden" name="wed_to" x-model="selectedDays.wed.to">
                <%= render(DayAvailabilityFieldComponent.new(label: "Wed", selected: true, model: "selectedDays.wed")) %>
                <input type="hidden" name="thu_selected" x-model="selectedDays.thu.selected">
                <input type="hidden" name="thu_from" x-model="selectedDays.thu.from">
                <input type="hidden" name="thu_to" x-model="selectedDays.thu.to">
                <%= render(DayAvailabilityFieldComponent.new(label: "Thu", selected: true, model: "selectedDays.thu")) %>
                <input type="hidden" name="fri_selected" x-model="selectedDays.fri.selected">
                <input type="hidden" name="fri_from" x-model="selectedDays.fri.from">
                <input type="hidden" name="fri_to" x-model="selectedDays.fri.to">
                <%= render(DayAvailabilityFieldComponent.new(label: "Fri", selected: true, model: "selectedDays.fri")) %>
                <input type="hidden" name="sat_selected" x-model="selectedDays.sat.selected">
                <input type="hidden" name="sat_from" x-model="selectedDays.sat.from">
                <input type="hidden" name="sat_to" x-model="selectedDays.sat.to">
                <%= render(DayAvailabilityFieldComponent.new(label: "Sat", selected: false, model: "selectedDays.sat")) %>
            </div>
        </div>
        <div class="border-t py-4 px-8 flex flex-row justify-end">
            <button type="submit" class="bg-blue-500 rounded py-2 px-4 text-sm text-gray-100" @click="availabilityModalOpen = false">
            Save
            </button>
        </div>
    </div>
    <% end %>
</div>

world/app/views/me/index.html.erb
<%= render :partial => "shared/responsive_navbar", :locals => { active_menu: "profile" } %>

<section class="w-full py-8">
  <div class="w-full max-w-4xl grid grid-cols-3 md:grid-cols-6 lg:grid-cols-8 mx-auto gap-x-8 gap-y-4 px-4 lg:px-0">
    <div class="col-span-1 md:col-span-2 lg:col-span-3">
        <%= render :partial => "shared/large_profile_picture", :locals => { user: @me } %>
    </div>
    <div class="col-span-2 md:col-span-4 lg:col-span-5">
        <h2 class="text-2xl font-bold text-slate-800"><%= @me.fullname %></h2>
        <%= render :partial => "editable_bio", :locals => { text: @me.bio } %>
        <% if @me.skills.length > 0 %>
          <div class="mt-8">
            <ul class="m-0 p-0 flex flex-row flex-wrap gap-2 align-top justify-start">
              <% @me.skills.each do |skill| %>
                <li>
                  <%= render :partial => "shared/skill", :locals => { skill: skill, skills_users_assoc: skill.skills_users.find_by(skill_id: skill.id, user_id: @me.id) } %>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="mt-8">
          <div class="flex flex-row justify-between items-start">
            <div class="flex flex-row space-x-4 justify-center items-start">
              <div class="flex flex-row items-center justify-center w-12 text-slate-600">
                <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path fill="currentColor" d="M12 20a1 1 0 0 1-.437-.1C11.214 19.73 3 15.671 3 9a5 5 0 0 1 8.535-3.536l.465.465.465-.465A5 5 0 0 1 21 9c0 6.646-8.212 10.728-8.562 10.9A1 1 0 0 1 12 20z"/>
                </svg>
              </div>
              <div class="flex flex-col">
                <h3 class="font-bold text-slate-600 text-lg">
                  <%= render :partial => "me/my_mentor_status", :locals => { is_mentor: @me.is_mentor } %>
                </h3>
                <p class="text-sm text-gray-400 mt-2">Becoming a hero without cape.</p>
                
                <%= render :partial => "shared/mentor_availability_link", :locals => { is_mentor: @me.is_mentor } %>
              </div>
            </div>
            <div class="flex flex-row items-center justify-center w-12 h-12">
              <%= render :partial => "mentor_opt_in_button", :locals => { is_mentor: @me.is_mentor } %>
            </div>
          </div>
        </div>
    </div>
  </div>
</section>

world/app/views/me/show_mentor_availability.html.erb
<%= render :partial => "shared/responsive_navbar", :locals => { active_menu: "profile" } %>

<section class="w-full py-8 flex flex-col">
    <div class="flex flex-row w-full lg:max-w-4xl mx-auto px-4 lg:px-0 mb-4">
        <h1 class="text-2xl font-bold text-slate-800">My availability</h1>
    </div>
    <div class="flex flex-col-reverse gap-y-4 md:grid md:grid-cols-2 md:gap-x-4 w-full lg:max-w-4xl mx-auto px-4 lg:px-0">
        <div class="col-span-1">
            <%= render  partial: "mentor_available_date",
                        locals: {
                            selected_date: {
                                wday: Date.current.wday,
                                date: Date.current.day,
                                month: Date.current.month, 
                                year: Date.current.year
                            }
                        } %>

            <%#= render  "shared/event_data",
                        event_name: "availability_calendar:selected",
                        data_template: "dayjs('${ year }-${ month }-${ date }').format('ddd D MMM YYYY')" %>
        </div>
        <div class="col-span-1">
            <div class="w-full aspect-1">
                <%= render  "shared/calendar",
                            month: Date.current.month, 
                            year: Date.current.year,
                            identifier: "availability_calendar" %>
            </div>
        </div>
    </div>
</section>